### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by DhrMaes** [Evidlo/remarkable_mouse#14]
Would be amazing if there was an installation guide explaning how to install it on a freshly bought reMarkable.

**Comment by Evidlo** [comment]
There is nothing to install on the remarkable.  You install the tool
through pip and use it.

**Comment by DhrMaes** [comment]
I tried to install it through ssh and typing "pip install remarkable-mouse" like you said in the readme file, but it always gave the same message "pip command not found".

**Comment by Evidlo** [comment]
No, the tool is installed/run on the host machine.

**Comment by DhrMaes** [comment]
Thank you very much for the extremely fast answers.
I do have one last question.
![image](https://user-images.githubusercontent.com/45536239/68335332-8f960480-00dc-11ea-9521-bb1c909ffc1d.png)
I keep getting a syntax error after I try to run it.
(I probably do something wrong though)

So I installed the newest version of python 2 and runned the installer.
Then I tried the 'remouse address monitor orientation password' and get this.

**Comment by Evidlo** [comment]
Its python3 only.

**Comment by DhrMaes** [comment]
I knew I dit something stupid. Thank you very much Imma try it.

**Comment by Evidlo** [comment]
Also, be warned: I haven't ever tested this on Windows.

**Comment by DhrMaes** [comment]
I'll let you know if I get any problems.

It's working just fine yet again thank you so much for helping me out. 
I'll close this issue.
