### ISSUE TITLE
Report pressure to the host

### ISSUE THREAD

**Issue by severin-lemaignan** [Evidlo/remarkable_mouse#15]
While `remarkable_mouse` does have access to the pressure information from the tablet, it is not reported to the host operating system, as `pynput` does not support it. This is unfortunate, as many graphic applications would benefit a lot of having that information.

Maybe one option would be to use a module like [`python-uinput`](https://pypi.org/project/python-uinput/) to recreate a fake input device?

**Comment by Evidlo** [comment]
Have you tried the `--evdev` option?

**Comment by skadge** [comment]
...the --evdev option? I haven't seen any such option in remarkable_mouse.py' ArgumentParser... Have I missed something?

**Comment by severin-lemaignan** [comment]
Haha!! I missed the `combined` branch! Excellent! Any plan to merge it to master any time soon? (in the meantime, maybe a note in the `README` could make it easier to discover!)

**Comment by Evidlo** [comment]
I thought it was already merged :o

**Comment by Evidlo** [comment]
This is merged and published now.
