### ISSUE TITLE
SSH connection error

### ISSUE THREAD

**Issue by ferqui** [Evidlo/remarkable_mouse#17]
When I try to SHH the remarkable, it gives me the following error:
`ssh_exchange_identification: read: Connection reset by peer`
Any idea how to solve it?

**Comment by Evidlo** [comment]
Is this the output you get from `remouse` or `ssh`?

**Comment by ferqui** [comment]
From both, remouse and ssh. I tried to use the remouse 
and it give me the following error: `paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 54] Connection reset by peer` 
So I tried to ssh into the device but it give me the same error, so I cannot get into the device.

**Comment by Evidlo** [comment]
If ssh has the same problem, then it's not an issue with remarkable_mouse.  Maybe try ssh with the -v option to get more debug info?

**Comment by ferqui** [comment]
I think it doesn't give any relevant information:
```
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/ferqui/.ssh/config
debug1: /Users/ferqui/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to 192.168.1.15 [192.168.1.15] port 22.
debug1: Connection established.
debug1: identity file /Users/ferqui/.ssh/id_rsa type 0
debug1: identity file /Users/ferqui/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
ssh_exchange_identification: read: Connection reset by peer
```
The connection is established but also finished by the RM.

**Comment by Evidlo** [comment]
I know some people were having trouble sshing into firmware 2.0.2.0.  Updating to the latest version seems to have fixed it for them.

**Comment by ferqui** [comment]
Yes, the problem was the firmware of the Remarkable. I recently received the update and the problem was solved. Thanks :)
