### ISSUE TITLE
evdev: libinput ignores the events because tablet resolution is missing

### ISSUE THREAD

**Issue by skadge** [Evidlo/remarkable_mouse#18]
Step to reproduce on Ubuntu 19.10, running wayland:

- start `remouse` like that:
```
$ sudo remouse --evdev --key ~/.ssh/remarkable
Created virtual input device '/dev/input/event5'
```

- no virtual tablet is created/visible

- Running `libinput list-devices` return the following error:
```
$ sudo libinput list-devices
event5  - reMarkable tablet: libinput bug: missing tablet capabilities: resolution. Ignoring this device.
```

According to [`libinput` documentation](https://wayland.freedesktop.org/libinput/doc/1.12.6/tablet-debugging.html), we need to specify the resolution of the tablet in a `60-evdev.hwdb` entry.

**Comment by skadge** [comment]
Adding the following lines to `/lib/udev/hwdb.d/60-evdev.hwdb`:

```
evdev:input:b0018v056Ap0000*
 EVDEV_ABS_00=::20
 EVDEV_ABS_01=::20 lines to `
```

Followed by:
```
$ sudo systemd-hwdb update
$ sudo udevadm trigger /dev/input/event5
```

And finally restarting `remouse` fixes the problem.

**Two important notes:**

- the value after `evdev:input` is the modalias of the tablet. You might want to check how it appears on your system: `cat /sys/devices/virtual/input/input58/modalias`
- I'm not sure about the actual resolution of the tablet, but 20 units/mm seems not too far off (the resulting behaviour of the tablet was ok)

**Comment by chabad360** [comment]
I hate to be a bother, but I'm having this issue as well.

**Comment by Evidlo** [comment]
Can anyone test if [this](https://python-libevdev.readthedocs.io/en/latest/libevdev.html#libevdev.device.Device.absinfo).

Then in `evdev.py` whilst setting up the device

    device.absinfo[libevdev.EV_ABS.ABS_X] = InputAbsInfo(resolution=2531)
    device.absinfo[libevdev.EV_ABS.ABS_Y] = InputAbsInfo(resolution=2531)

Not sure if these resolutions are correct.  It seems like it should be specified in dpi here, which I computed for the digitizer.  Does the error go away at least?

**Comment by chabad360** [comment]
Where would I put it?

**Comment by Evidlo** [comment]
After `device` is created and before it is returned.

**Comment by chabad360** [comment]
I stuck it over here:
```python
...
   # Enable position, tilt, distance and pressure change events
    device.enable(
        libevdev.EV_ABS.ABS_X,
        libevdev.InputAbsInfo(
            minimum=0,
            maximum=MAX_ABS_X,
            resolution=2531
        )
    )
    device.enable(
        libevdev.EV_ABS.ABS_Y,
        libevdev.InputAbsInfo(
            minimum=0,
            maximum=MAX_ABS_Y,
            resolution=2531
        )
    )
...
```

**Comment by chabad360** [comment]
Further testing revealed a slight lack of alignment, but that was fixed with `--mode fill`. So it seems to have worked (yay)!

**Comment by chabad360** [comment]
@Evidlo mmm... it seems like the alignment issues persist, so either the resolution is wrong, or there is something wrong with `remap()`
