### ISSUE TITLE
Reduced space on the reMarkable for writing

### ISSUE THREAD

**Issue by sr1920** [Evidlo/remarkable_mouse#21]
I had to modify the pynput.py to make this work on MacOS. As suggested in another thread, I added this to avoid the call to get_monitors:
    monitor = Monitor(
            x=0,
            y=0,
            width=2560,
            height=1440
        )
The data above correspond with the resolution of my screen. Besides, I have been able to obtain those data using screeninfo in a simple Python script of my own.

Then I can run "remouse --orientation vertical" successfully, but the problem is that an important part of the top of the reMarkable screen correspond to the top part of my MacOS screen (i.e., I have to start writing on the reMarkable without using about 1/3 of its screen at the top).

Not sure if this behavior is expected...

**Comment by Evidlo** [comment]
That's not normal.  The normal behavior is that the tablet input is scaled so that the entire monitor is covered.

**Comment by Evidlo** [comment]
> I think that a different scaling should be considered for the X and Y

Probably not a good idea.  Whatever you draw on the tablet will squished in the X or Y direction on the monitor.

I added a `--mode` option with the latest commit on master to switch between fit and fill modes.

![](http://mayanphoto.com/images/aspect_ratio_fitfill.jpg)

I'm still confused why you're seeing this because the previous behavior was to fill the monitor.

> I'm not sure about the meaning of the width_mm and height_mm parameters 

The only parameters I use from screeninfo.Monitor are the screen size (width, height) and offset (x, y).

**Comment by Evidlo** [comment]
Is this still an issue?  Have you tested since those commits I mentioned?

**Comment by sr1920** [comment]
I have just tried with the last version, but I get an error:

.../opt/anaconda3/lib/python3.7/site-packages/screeninfo/screeninfo.py", line 47, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available

The previous version (with the modifications I indicated) still works for me.

**Comment by sr1920** [comment]
Two clarifications:

1) Sorry, I didn't remember that this error also happened before with the previous version and I solved it by avoiding the call to get_monitors (as I indicated in a previous message above). With this change, the new version seems to work well without any adjustments when my space is the whole screen.

2) However, I have a specific use case where I restrict the area of the screen where I want the application to work (e.g., I create a window in Paint and I want the mouse to move only within that window). For that purpose, I define the boundaries of my window as if they were the boundaries of the whole screen; e.g.:

monitor = Monitor(
            x=0,
            y=47,
            width=918,
            height=690,
            #width_mm=310, 
            #height_mm=174
       )

In this case, the behavior is still wrong. My modified version with the scaling hack mentioned above behaves well in this scenario.

**Comment by Evidlo** [comment]
Let me know if this is still an issue.
