### ISSUE TITLE
evdev ignores monitor

### ISSUE THREAD

**Issue by peteh** [Evidlo/remarkable_mouse#24]
Looks like the evdev option ignores the monitor and scales over the whole screen (i have dual screen in extension mode). So instead of being locked into on of the screen it scales the whole remarkable surface to both screens stretching it. 

Expectation: --monitor parameter selects to scale on the selected screen.

**Comment by Evidlo** [comment]
This is a known issue.  I've been working on adding support for `--monitor` and related options, but it's not on master yet.  In the meantime, you can use the xinput commands listed here: https://github.com/Evidlo/remarkable_mouse/pull/9

**Comment by peteh** [comment]
Thank you it works! Great tool!

**Comment by catskul** [comment]
https://github.com/Evidlo/remarkable_mouse/pull/26 allows use of gnome settings to map to monitor.

**Comment by Evidlo** [comment]
`--mode`, `--orientation`, and `--monitor` are supported in evdev mode now.
