### ISSUE TITLE
Changing the size of the input area on the tablet

### ISSUE THREAD

**Issue by AugCa** [Evidlo/remarkable_mouse#25]
Loving this script so far and want to experiment with the wide array of possibilities. Is there any semi-easy way to configure the input area to use a smaller area of the tablet for games like osu? I saw that LinusCDE who inspired you to make achieved this but his solution seemed rather complex and I'm not experienced enough to apply his solution without possibly breaking something.

**Comment by Evidlo** [comment]
If you're on Linux, you can use ` xinput --set-prop "reMarkable tablet stylus" "Wacom Tablet Area" x y X Y` to set the input area.

For example `xinput --set-prop "reMarkable tablet stylus" "Wacom Tablet Area" 0 0 7500 7500` will use approximately 1/4 of the tablet's 20967x15725 digitizer.

You could also modify the `scale` option in the remap function in `pynput.py` to whatever you want.

**Comment by AugCa** [comment]
First solution worked perfectly, thank you!
