### ISSUE TITLE
failed to create process

### ISSUE THREAD

**Issue by StLa1** [Evidlo/remarkable_mouse#28]
Hello, I could make it work once, but now for some reason I get "failed to create process". What should I do ? Thx 

```
C:\Users\stnsl>remouse
failed to create process.
```

**Comment by ksmithdev** [comment]
This can happen when when python is installed to a path with a space in it.
https://stackoverflow.com/q/34057783/225565

**Comment by Evidlo** [comment]
Let me know if this is still an issue.
