### ISSUE TITLE
Can't stop process on windows when running Terminal

### ISSUE THREAD

**Issue by ksmithdev** [Evidlo/remarkable_mouse#29]
I'm running remouse on Windows 10 (19041.330) inside Powershell (7.0.2) using Windows Terminal (1.0.1401.0). It works great but I can't seem to stop the process using CTRL+C. Am I missing something?

(as an aside, this is an awesome utility for the remarkable!!)

**Comment by Evidlo** [comment]
That's normally the correct way on most shells.

https://stackoverflow.com/questions/42039231/ctrl-c-for-quitting-python-in-powershell-now-not-working
