### ISSUE TITLE
SSH key format issue, paramiko

### ISSUE THREAD

**Issue by wrought** [Evidlo/remarkable_mouse#3]
paramiko.ssh_exception.SSHException: not a valid RSA private key file

I guess I'm using a newer version of openssh. Not sure why this hasn't been handled upstream yet, but it's pretty annoying. The workaround mentioned here to generate new keys seems to have worked:

    ssh-keygen -m PEM -t rsa

https://github.com/paramiko/paramiko/issues/1015#issuecomment-456718718

**Comment by raffraffraff** [comment]
So it doesn't work with ed25519 keys?

**Comment by Evidlo** [comment]
Should be fixed now.  Let me know if it isn't.
