### ISSUE TITLE
does not work on Ubuntu 20.04 with reMarkable 2

### ISSUE THREAD

**Issue by Stivanification** [Evidlo/remarkable_mouse#36]
This does not appear to be working for me. I did the pip install and after executing `remouse` I get the message `connected to 10.11.99.1` however I can't get the mouse to move.

**Comment by jonahweissman** [comment]
This is being worked on in #32

**Comment by Evidlo** [comment]
Try the `rm2` branch.

**Comment by jonahweissman** [comment]
Thanks! The `rm2` branch picks the right input device for me. However, the cursor lags a little. Specifically, if I quickly move my marker in circles, the mouse will keep moving in circles for a bit after I stop moving my marker. As a workaround, I had `pynput` only update the mouse position with probability 0.05.

I'm happy to open a new issue and discuss there, if that'd be easier.

**Comment by Pemo11235** [comment]
I tried, and it works ! 
Great work and thanks !

**Comment by Evidlo** [comment]
@jonahweissman Sure
