### ISSUE TITLE
mouse input is stuttering on Windows

### ISSUE THREAD

**Issue by TermoZour** [Evidlo/remarkable_mouse#37]
The lib is working perfectly fine on Linux (to be exact, Pop!OS 20.10)
On Windows, the mouse stutters (like it doesn't have enough resolution). You can see it jump from Point A to Point B when swiping fast. [video here](https://drive.google.com/file/d/1So6IppN1Z-IUg0NSiAKADrGFA0jkRHRZ/view?usp=sharing)

The smooth one is moving the mouse directly, the laggy one is using the reMarkable.

**Comment by Evidlo** [comment]
Yes I've seen this.  I haven't verified it, but I think its a problem in
pynput.

**Comment by TermoZour** [comment]
Is there anything I can try on my end? I've seen on other issues that you
don't have access to a Windows machine.

**Comment by Evidlo** [comment]
You could try this snippet and see how it performs:

``` python
import math
from pynput.mouse import Controller
import time

start = time.time()

mouse = Controller()

mouse.move(100, 100)

N = 100
for n in range(2 * N):
    rad = 2 * math.pi * n / N

    mouse.position = (
        200 * math.cos(rad) + 500,
        200 * math.sin(rad) + 500
    )

    time.sleep(.01)


print('total:', time.time() - start)
```

**Comment by TermoZour** [comment]
It works smoothly. [video here](https://drive.google.com/file/d/15hdxouwfo0-12LsBVQPoJDon5jqcMIdG/view?usp=sharing)

**Comment by petergroves81** [comment]
I'm using remarkable_mouse on Windows 10. The cursor seems to move OK but when I try to write or draw something (in Windows Journal or Paint 3D) nothing appears on screen until I lift the pen from the ReMarkable, whereupon a straight line appears on my screen joining the starting point and the finishing point.

**Comment by Evidlo** [comment]
[Here](https://github.com/Evidlo/remarkable_mouse/blob/simple/remouse.py) is a stripped down version of the code which should help figure out what's causing the latency.

**Comment by TermoZour** [comment]
I've just tested it and I still get the same weird latency.

**Comment by Evidlo** [comment]
Right, the purpose of that code is just to make it easier for others to poke around and figure out the cause.

**Comment by Evidlo** [comment]
I've narrowed the problem down a bit on Windows: https://github.com/paramiko/paramiko/issues/1801

**Comment by DDorch** [comment]
@petergroves81, I had the same issue on Paint3D but it works fine on Gimp. (I used the rm2 branch with a Remarkable2).

**Comment by nils-werner** [comment]
I can [improve performance significantly by setting `bufsize=16` and `timeout=0`](https://github.com/nils-werner/remarkable_mouse/tree/bufsize_timeout).
