### ISSUE TITLE
Support for remarkable2

### ISSUE THREAD

**Issue by marsop** [Evidlo/remarkable_mouse#42]
Hi, 

I wanted to try this for the reMarkable2. It turns out that the event file is different from rM1:

`/dev/input/event0` => `/dev/input/event1`

I think one extra command line arg (something like `--remarkable2`) would help future users of this library without breaking backwards compatibility.

**Comment by YHRen** [comment]
likely duplicate. see #32

**Comment by marsop** [comment]
Right you are. Duplicate of #32
