### ISSUE TITLE
Couldn't make it work on Windows 10

### ISSUE THREAD

**Issue by SuperFola** [Evidlo/remarkable_mouse#44]
Hi!

I'm deeply interested in using this on my computer, but so far I've tried a WSL2+VCXSRV, it connected to the display but the mouse wasn't moving, same with an admin powershell or an admin cmd prompt, it connects but the mouse doesn't move.

The command I tried: `remouse --password XXXXXXXX --mode fit --orientation top --debug`

On powershell and cmd prompt I have this output:
```
connected to 10.11.99.1
Debugging enabled...
Chose monitor: Monitor(x=0, y=0, width=1920, height=1080, width_mm=293, height_mm=165, name='\\\\.\\DISPLAY1')
```

On WSL2, only the monitor changes

Thanks in advance

**Comment by wieltar** [comment]
How were you able to start the script? I installed it with pip3 but it does not recognise the remouse command

**Comment by SuperFola** [comment]
Pip installed it in my scripts folder which is in my path

**Comment by Evidlo** [comment]
You have to make sure you checked "Add Python to PATH" when installing Python

**Comment by wieltar** [comment]
I also have this problem now, it connects successfully but then doesn't do anything, i tried opening a notebook but still no output on the screen on the pc

**Comment by SuperFola** [comment]
Yes, apparently that one worked for me

**Comment by Evidlo** [comment]
The PATH issue seems to be resolved now.  Performance is bad on Windows (https://github.com/Evidlo/remarkable_mouse/issues/37), but you should still see mouse movement.
