### ISSUE TITLE
No argument --event-file

### ISSUE THREAD

**Issue by guhraman** [Evidlo/remarkable_mouse#45]
I'm trying to make remouse work with my RM2 and hence tried

**remouse --event-file /dev/input/event1**

However, my machine claims

**unrecognized arguments: --event-file /dev/input/event1**

In fact, when I run

**remouse -h**

I get

usage: remouse [-h] [--debug] [--key PATH] [--password PASSWORD]
               [--address ADDRESS] [--mode {fit,fill}]
               [--orientation {top,left,right,bottom}] [--monitor NUM]
               [--threshold THRESH] [--evdev]

use reMarkable tablet as a mouse input

optional arguments:
  -h, --help            show this help message and exit
  --debug               enable debug messages
  --key PATH            ssh private key
  --password PASSWORD   ssh password
  --address ADDRESS     device address
  --mode {fit,fill}     scale setting
  --orientation {top,left,right,bottom}
                        position of tablet buttons
  --monitor NUM         monitor to output to
  --threshold THRESH    stylus pressure threshold (default 600)
  --evdev               use evdev to support pen pressure (requires root,
                        Linux only)

Any suggestion as to what's wrong here and possible solutions?

**Comment by Pemo11235** [comment]
I had same issue , looking for a solution

**Comment by Evidlo** [comment]
`--event-file` was an argument added in a PR that was not merged.

Try the `rm2` branch and tell me if it works.

**Comment by Evidlo** [comment]
Move this discussion to https://github.com/Evidlo/remarkable_mouse/issues/36
