### ISSUE TITLE
--password parameter not working

### ISSUE THREAD

**Issue by mlgarchery** [Evidlo/remarkable_mouse#5]
I noticed that the --password parameter was not working, so I  downloaded the source and modified your code successfuly so that I can connect to my rM with: $ remouse --password \<password>. (i did a $ python setup.py install)
But then I have this error:
NameError: name 'WACOM_EVCODE_YPOS' is not defined
Do you know from where it come from ?

Thx

**Comment by mlgarchery** [comment]
Ok so I notice the code here ("version 3") differs from the one on PyPI https://pypi.org/project/remarkable-mouse/#files ("version 4") .
I downloaded the code from Pypi and it worked. I have a warning though:
*<python_path>/site-packages/paramiko-2.4.2-py3.6.egg/paramiko/kex_ecdh_nist.py:39: **CryptographyDeprecationWarning**: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())*

**Comment by Evidlo** [comment]
Should be fixed with v4.1
