### ISSUE TITLE
--evdev: pen doesn't work with RM2

### ISSUE THREAD

**Issue by akdor1154** [Evidlo/remarkable_mouse#50]
Hi,
Thanks for this awesome project.
I can't get --evdev to give me any pen input. Without --evdev everything seems to work OK, but with it I get touch events but no pen events. GIMP seems to recognize a pen input device being created but `remouse --debug` doesn't yield any event spam.

Ubuntu 20.10
Remarkable 2, latest firmware
#rm2 branch

--debug output:
```
sudo -E ~/.local/bin/remouse --key ~/.ssh/id_rsa  --debug --monitor 1 --orientation left --evdev                             
Debugging enabled...
Connecting to input '10.11.99.1'
Pen:/dev/input/event1
Touch:/dev/input/event2
Button:/dev/input/event0
Connected to 10.11.99.1
Created virtual input device '/dev/input/event21'
Chose monitor: Monitor(x=0, y=0, width=1920, height=1200, width_mm=518, height_mm=324, name='DVI-D-0')
Wacom tablet area: 0.0 1310.3125000000002 20967.0 14414.687500000002
Multi-touch area: 63.81249999999999 0.0 703.1875 1023.0
```

SSH'd to the rm2, running `xxd /dev/input/event1` seems to produce output from the pen as expected (though I can't interpret what it's saying because I'm not Keanu Reeves...)

I will have a play around as well, just touching base. :)

Jarrad

**Comment by akdor1154** [comment]
I guess something to do with evdev.py#287 where you only read touch and button events.. this seems intentional because when I loop through all events it works for a second or two and then breaks my PC input. I'll leave this alone for now assuming you know this doesn't work yet.

**Comment by andrewhowdencom** [comment]
I also did this! It also worked. Dope!

**Comment by malinkb** [comment]
> EDIT: Couldn't leave it alone :) when I change the loop to just process the pen input device then it seems to work perfectly! Though obviously touch and button do nothing.

Hi. How exactly did you do that? :)

**Comment by Evidlo** [comment]
Try with the most recent commit.  It only reads from the pen input.
