### ISSUE TITLE
Does not seem to work on Windows using rM2 on 2.7.0.51

### ISSUE THREAD

**Issue by gjerm** [Evidlo/remarkable_mouse#54]
Python version 3.9.5, Windows 10 build 19042.928. Installed the normal way (`pip install remarkable-mouse`)

I plug the rM2 in using USB and run `remouse --debug`. Output: 

```
Password for '10.11.99.1':
connected to 10.11.99.1
Debugging enabled...
Chose monitor: Monitor(x=2560, y=233, width=1920, height=1200, width_mm=518, height_mm=324, name='\\\\.\\DISPLAY1')
```

The process does not exit, but stays here. On the reMarkable nothing changes, and using the pen on the tablet works like normal (no UI changes, the PC does not react at all). 

Also had no luck trying different options (setting orientation to something different, choosing a different monitor or mode).

**Comment by fancypantalons** [comment]
I suspect this is a duplicate of #52.  Check out the workaround in that comment thread.

**Comment by gjerm** [comment]
Downloaded and installed from the rM2 branch, working great now :)
