### ISSUE TITLE
doesnt connect, issues with shh might be related. 

### ISSUE THREAD

**Issue by Memylicious** [Evidlo/remarkable_mouse#57]
when i try to connect it gives me an error about paramiko not being installed (i tried to use the sudo command cause one post said something about trying it in root) and i also saw something in another post about seeing wether or not you could connect to the tablet with shh and i did some research but i dont seem to have it, even when i installed openshh it didn't end up working, this might be the problem but this is completely out of my area of expertise, does anyone know what the issue might be or how i could solve it? (the same issue is happening with remouseable which i had used on windows and ubuntu before i just switched to arch and the problems started)

**Comment by Evidlo** [comment]
paramiko should automatically get installed when you install with pip.

You shouldn't use sudo with pip.  Just a `pip install remarkable-mouse` should be sufficient.
