### ISSUE TITLE
Issue with mouse events in browser

### ISSUE THREAD

**Issue by bordaigorl** [Evidlo/remarkable_mouse#6]
This is a great program! Thanks!

I managed to get it to work on my Mac (I had to bypass `screeninfo` because it could not really detect my monitor and had to hardcode the `Monitor` object but fine).
It works well with local applications like Gimp or Krita.
It does not work with apps like sketchboard.io or awwapp.com as it seems the mouse events confuse the app enormously.
I tried with both Firefox and Chrome.
Any idea of why that could be and how to fix it?

**Comment by Evidlo** [comment]
I have no idea why it wouldn't work with webapps.  It should work the same way with anything that uses a mouse.

**Comment by bordaigorl** [comment]
First, could you reproduce the issue?
I don't think it has to do with webapps specifically but I think the ones I am using are expecting to see some event sequence and are very confused by the one produced by the program.
I get inconsistent behaviour with drag&drop in the OS too, and for text selection.
What I observe looks like a "mouseup" event interrupting randomly and frequently the drag&drop.
This happens no matter which threshold I use.
Try for example drag&dropping windows around. Do you experience any problem?

**Comment by Evidlo** [comment]
So what does `get_monitors()` return?  Sounds like an upstream bug in `screeninfo`.

**Comment by bordaigorl** [comment]
I get a `NotImplemented` exception, saying that the enumerator is not available in my environment.
I wrote this PR because, in addition to allowing workarounds to this problem, these option may make sense in non standard situations, while making normal use as easy as before.

**Comment by Evidlo** [comment]
Here's the PR that supposedly added OSX support to screeninfo: https://github.com/rr-/screeninfo/pull/4/files

**Comment by DavidValin** [comment]
I use python3, installed latest screeninfo and built remarkable_mouse, OSX 10.12.6. I get:

`Traceback (most recent call last):
  File "remarkable_mouse.py", line 183, in <module>
    main()
  File "remarkable_mouse.py", line 177, in main
    read_tablet(args)
  File "remarkable_mouse.py", line 111, in read_tablet
    monitor = get_monitors()[args.monitor]
  File "/usr/local/lib/python3.7/site-packages/screeninfo/screeninfo.py", line 29, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available`

**Comment by bordaigorl** [comment]
@DavidValin check out my PR #8 it adds options to bypass `screeninfo` and specify the screen size manually (maybe this thread should be moved there)
