### ISSUE TITLE
Warranty concerns

### ISSUE THREAD

**Issue by SBAPKat** [Evidlo/remarkable_mouse#62]
Hello,
I've taken some time reading bits of the code and it looks like it doesn't actually make any change to the tablet, 
Am I correct to assume that this is essentially just connecting via SSH to read the 3 devices?
Meaning the warranty shouldn't pop, If I'm right, I believe it would be good to have it shown on the main page, so more people take interest in this project

**Comment by Evidlo** [comment]
>  Am I correct to assume that this is essentially just connecting via SSH to read the 3 devices?

That's correct.  I haven't read reMarkable's EULA, so I don't know what the warranty actually covers.  I think it gets pretty complicated depending on what country you reside in, so I'm not sure putting this in the README will do much.
