### ISSUE TITLE
Tablet active area

### ISSUE THREAD

**Issue by SBAPKat** [Evidlo/remarkable_mouse#66]
Hi,
Since the tablet is so big, sometimes when using a small monitor it feels weird having such a big area, 
That's why i suggest adding a tablet area setting so that we can increase its "sensitivity"

**Comment by Evidlo** [comment]
Have you tried using the `--region` option?

**Comment by aikenahac** [comment]
Hey, the region option doesn't work for me
![Screenshot_2022-01-19-09_805x460](https://user-images.githubusercontent.com/30961404/150122870-175804fe-8eb2-453d-bef1-c3aee3a8c7d1.png)
.

**Comment by SBAPKat** [comment]
the --region option limits your screen area, not the tablet area if i'm not mistaken. I've crudely fixed this on my local version by adding an argument which supplies a multiplier to the return values of remap. I've found a value of 2 to be more manageable for me, I've also fixed the --password argument (broken atm), would you like a pull request ?

**Comment by SBAPKat** [comment]
@aikenahac you actually need to uninstall the pip version of remarkable_mouse and install it from the main branch using the setup script. Pip's version isn't up to date

**Comment by aikenahac** [comment]
> @aikenahac you actually need to uninstall the pip version of remarkable_mouse and install it from the main branch using the setup script. Pip's version isn't up to date

Ahh alright. Thanks.

**Comment by Evidlo** [comment]
Should be fixed in 7.0.0

**Comment by SBAPKat** [comment]
This issue wasn't about a fix but a Feature addition, 
Currently the software allows modification of the controlled area of the screen via --region, but I'm looking for a feature to reduce the tablet area, while still controlling the entire screen, thus increasing sensitivity
