### ISSUE TITLE
--orientation doesn't work with --evdev enabled

### ISSUE THREAD

**Issue by dpaleka** [Evidlo/remarkable_mouse#74]
The command `remouse --orientation top` behaves as expected, but `remouse --evdev --orientation top` has no effect; the orientation is always with the main button on the left.

Versions:
- Remarkable: RM1 
- Remarkable software: `2.13.0.639`
- `remarkable_mouse`: `7.0.2` 
- `uname -r` gives `5.15.28-1-MANJARO`
- `xpdyinfo | grep version` gives `X.Org version: 1.21.1.3`

**Comment by kororos** [comment]
The same issue exists with RM2. Additionally the --monitor option and the --mode also seem to be ignored.

**Comment by Evidlo** [comment]
This should be fixed in 7.0.3

**Comment by kororos** [comment]
After upgrading to 7.0.3 there still seem to be issues with the scaling/mapping. In both fill and fit modes, the aspect ratio between the tablet and monitor are not equal. Simple test was to draw a (near perfect) circle on rM and see that it is distorted on the monitor. 

My config: 

Monitor 1: 2560x1440 (primary)
Monitor 0: 1680x1050

Command: 
remouse --monitor 1 --password masked   --mode fill --evdev 

Note: Without using --evdev, ratio is fine.

**Comment by Evidlo** [comment]
@kororos Can you try with 7.1.0?  I think it's fixed now.
